2015-05-26 18:06:49,635 - [INFO] - from play in pool-8-thread-1 
Listening for HTTP on /0:0:0:0:0:0:0:0%0:9000

2015-05-26 18:06:53,337 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:mysql://localhost:3306/notification_engine

2015-05-26 18:06:53,490 - [INFO] - from org.reflections.Reflections in play-internal-execution-context-1 
Reflections took 79 ms to scan 2 urls, producing 16 keys and 31 values 

2015-05-26 18:06:53,771 - [INFO] - from com.avaje.ebeaninternal.server.core.DefaultServerFactory in play-internal-execution-context-1 
DatabasePlatform name:default platform:mysql

2015-05-26 18:06:53,994 - [INFO] - from com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager in play-internal-execution-context-1 
Entities enhanced[3] subclassed[0]

2015-05-26 18:06:54,481 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2015-05-26 18:06:54,871 - [INFO] - from akka.event.slf4j.Slf4jLogger in play-akka.actor.default-dispatcher-3 
Slf4jLogger started

2015-05-26 18:06:55,045 - [INFO] - from com.twilio.sdk.resource.instance.Application in play-akka.actor.default-dispatcher-5 
Sending message request: [To=17734845887, From=+17084876341, Body="Hello", StatusCallback=http://42a2173c.ngrok.io/status]

2015-05-26 18:06:56,404 - [INFO] - from org.hibernate.validator.internal.util.Version in play-akka.actor.default-dispatcher-4 
HV000001: Hibernate Validator 5.0.1.Final

2015-05-26 18:06:56,583 - [ERROR] - from controllers.Application in play-akka.actor.default-dispatcher-5 
javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[Unknown column 'to_number' in 'field list']

2015-05-26 18:06:56,847 - [INFO] - from org.avaje.ebean.TXN in play-akka.actor.default-dispatcher-5 
txn[1002] Rollback

2015-05-26 18:06:56,847 - [INFO] - from org.avaje.ebean.TXN in play-akka.actor.default-dispatcher-4 
txn[1003] Rollback

2015-05-26 18:06:56,848 - [ERROR] - from play in play-internal-execution-context-1 
Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: Query threw SQLException:Unknown column 't0.to_number' in 'field list' 
Bind values:[SM1619453681484e1eac114c423b535a1f] 
Query was:
select t0.message_type c0, t0.id c1, t0.from_number c2, t0.to_number c3, t0.account_id c4, t0.content c5, t0.status c6, t0.created_at c7, t0.updated_at c8 from messages t0 where t0.message_type = 'SMS'  and t0.id = ?   



2015-05-26 18:06:56,848 - [ERROR] - from play in play-internal-execution-context-2 
Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: Query threw SQLException:Unknown column 't0.to_number' in 'field list' 
Bind values:[SM1619453681484e1eac114c423b535a1f] 
Query was:
select t0.message_type c0, t0.id c1, t0.from_number c2, t0.to_number c3, t0.account_id c4, t0.content c5, t0.status c6, t0.created_at c7, t0.updated_at c8 from messages t0 where t0.message_type = 'SMS'  and t0.id = ?   



2015-05-26 18:06:56,878 - [ERROR] - from application in play-internal-execution-context-1 


! @6m9k39a6c - Internal server error, for (POST) [/status] ->

play.api.Application$$anon$1: Execution exception[[PersistenceException: Query threw SQLException:Unknown column 't0.to_number' in 'field list' 
Bind values:[SM1619453681484e1eac114c423b535a1f] 
Query was:
select t0.message_type c0, t0.id c1, t0.from_number c2, t0.to_number c3, t0.account_id c4, t0.content c5, t0.status c6, t0.created_at c7, t0.updated_at c8 from messages t0 where t0.message_type = 'SMS'  and t0.id = ?   

]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.3]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) [play-iteratees_2.10.jar:2.2.3]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
Caused by: javax.persistence.PersistenceException: Query threw SQLException:Unknown column 't0.to_number' in 'field list' 
Bind values:[SM1619453681484e1eac114c423b535a1f] 
Query was:
select t0.message_type c0, t0.id c1, t0.from_number c2, t0.to_number c3, t0.account_id c4, t0.content c5, t0.status c6, t0.created_at c7, t0.updated_at c8 from messages t0 where t0.message_type = 'SMS'  and t0.id = ?   


	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:790) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:767) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.find(CQueryEngine.java:250) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findId(DefaultOrmQueryEngine.java:118) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findId(OrmQueryRequest.java:231) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findId(DefaultServer.java:1193) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.find(DefaultServer.java:1046) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.find(DefaultServer.java:1033) ~[avaje-ebeanorm.jar:na]
	at play.db.ebean.Model$Finder.byId(Model.java:261) ~[play-java-ebean_2.10.jar:2.2.3]
	at controllers.Application.status(Application.java:151) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$5$$anonfun$apply$5.apply(routes_routing.scala:101) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$5$$anonfun$apply$5.apply(routes_routing.scala:101) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[play_2.10.jar:2.2.3]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[play_2.10.jar:2.2.3]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) ~[akka-actor_2.10.jar:2.2.0]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) ~[akka-actor_2.10.jar:2.2.0]
	... 4 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 't0.to_number' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_65]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[na:1.6.0_65]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_65]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_65]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3558) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3490) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1959) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2109) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2648) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2077) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2228) ~[mysql-connector-java-5.1.10.jar:na]
	at com.jolbox.bonecp.PreparedStatementHandle.executeQuery(PreparedStatementHandle.java:174) ~[bonecp.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.prepareBindExecuteQuery(CQuery.java:377) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.find(CQueryEngine.java:231) ~[avaje-ebeanorm.jar:na]
	... 26 common frames omitted

2015-05-26 18:06:56,878 - [ERROR] - from application in play-internal-execution-context-2 


! @6m9k39a6c - Internal server error, for (POST) [/status] ->

play.api.Application$$anon$1: Execution exception[[PersistenceException: Query threw SQLException:Unknown column 't0.to_number' in 'field list' 
Bind values:[SM1619453681484e1eac114c423b535a1f] 
Query was:
select t0.message_type c0, t0.id c1, t0.from_number c2, t0.to_number c3, t0.account_id c4, t0.content c5, t0.status c6, t0.created_at c7, t0.updated_at c8 from messages t0 where t0.message_type = 'SMS'  and t0.id = ?   

]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.3]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) [play-iteratees_2.10.jar:2.2.3]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
Caused by: javax.persistence.PersistenceException: Query threw SQLException:Unknown column 't0.to_number' in 'field list' 
Bind values:[SM1619453681484e1eac114c423b535a1f] 
Query was:
select t0.message_type c0, t0.id c1, t0.from_number c2, t0.to_number c3, t0.account_id c4, t0.content c5, t0.status c6, t0.created_at c7, t0.updated_at c8 from messages t0 where t0.message_type = 'SMS'  and t0.id = ?   


	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:790) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:767) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.find(CQueryEngine.java:250) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findId(DefaultOrmQueryEngine.java:118) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findId(OrmQueryRequest.java:231) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findId(DefaultServer.java:1193) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.find(DefaultServer.java:1046) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.find(DefaultServer.java:1033) ~[avaje-ebeanorm.jar:na]
	at play.db.ebean.Model$Finder.byId(Model.java:261) ~[play-java-ebean_2.10.jar:2.2.3]
	at controllers.Application.status(Application.java:151) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$5$$anonfun$apply$5.apply(routes_routing.scala:101) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$5$$anonfun$apply$5.apply(routes_routing.scala:101) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[play_2.10.jar:2.2.3]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[play_2.10.jar:2.2.3]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) ~[akka-actor_2.10.jar:2.2.0]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) ~[akka-actor_2.10.jar:2.2.0]
	... 4 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 't0.to_number' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_65]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[na:1.6.0_65]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_65]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_65]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3558) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3490) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1959) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2109) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2648) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2077) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2228) ~[mysql-connector-java-5.1.10.jar:na]
	at com.jolbox.bonecp.PreparedStatementHandle.executeQuery(PreparedStatementHandle.java:174) ~[bonecp.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.prepareBindExecuteQuery(CQuery.java:377) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.find(CQueryEngine.java:231) ~[avaje-ebeanorm.jar:na]
	... 26 common frames omitted

2015-05-26 18:06:58,518 - [INFO] - from com.twilio.sdk.resource.instance.Application in play-akka.actor.default-dispatcher-5 
Sending message request: [To=17734845887, From=+15005550006, Body="Hello", StatusCallback=http://42a2173c.ngrok.io/status]

2015-05-26 18:06:58,723 - [ERROR] - from controllers.Application in play-akka.actor.default-dispatcher-5 
com.twilio.sdk.TwilioRestException: The From phone number +15005550006 is not a valid, SMS-capable inbound phone number or short code for your account.

2015-05-26 18:07:00,278 - [INFO] - from com.twilio.sdk.resource.instance.Application in play-akka.actor.default-dispatcher-4 
Sending message request: [To=17734845887, From=+17084876341, Body="Hello", StatusCallback=http://42a2173c.ngrok.io/status]

2015-05-26 18:07:00,575 - [ERROR] - from controllers.Application in play-akka.actor.default-dispatcher-4 
javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[Unknown column 'to_number' in 'field list']

2015-05-26 18:07:00,708 - [INFO] - from org.avaje.ebean.TXN in play-akka.actor.default-dispatcher-5 
txn[1005] Rollback

2015-05-26 18:07:00,709 - [ERROR] - from play in play-internal-execution-context-2 
Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: Query threw SQLException:Unknown column 't0.to_number' in 'field list' 
Bind values:[SMbfe4db0973714561bb865e4592276ff1] 
Query was:
select t0.message_type c0, t0.id c1, t0.from_number c2, t0.to_number c3, t0.account_id c4, t0.content c5, t0.status c6, t0.created_at c7, t0.updated_at c8 from messages t0 where t0.message_type = 'SMS'  and t0.id = ?   



2015-05-26 18:07:00,715 - [ERROR] - from application in play-internal-execution-context-2 


! @6m9k39fo6 - Internal server error, for (POST) [/status] ->

play.api.Application$$anon$1: Execution exception[[PersistenceException: Query threw SQLException:Unknown column 't0.to_number' in 'field list' 
Bind values:[SMbfe4db0973714561bb865e4592276ff1] 
Query was:
select t0.message_type c0, t0.id c1, t0.from_number c2, t0.to_number c3, t0.account_id c4, t0.content c5, t0.status c6, t0.created_at c7, t0.updated_at c8 from messages t0 where t0.message_type = 'SMS'  and t0.id = ?   

]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.3]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) [play-iteratees_2.10.jar:2.2.3]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
Caused by: javax.persistence.PersistenceException: Query threw SQLException:Unknown column 't0.to_number' in 'field list' 
Bind values:[SMbfe4db0973714561bb865e4592276ff1] 
Query was:
select t0.message_type c0, t0.id c1, t0.from_number c2, t0.to_number c3, t0.account_id c4, t0.content c5, t0.status c6, t0.created_at c7, t0.updated_at c8 from messages t0 where t0.message_type = 'SMS'  and t0.id = ?   


	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:790) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:767) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.find(CQueryEngine.java:250) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findId(DefaultOrmQueryEngine.java:118) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findId(OrmQueryRequest.java:231) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findId(DefaultServer.java:1193) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.find(DefaultServer.java:1046) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.find(DefaultServer.java:1033) ~[avaje-ebeanorm.jar:na]
	at play.db.ebean.Model$Finder.byId(Model.java:261) ~[play-java-ebean_2.10.jar:2.2.3]
	at controllers.Application.status(Application.java:151) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$5$$anonfun$apply$5.apply(routes_routing.scala:101) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$5$$anonfun$apply$5.apply(routes_routing.scala:101) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[play_2.10.jar:2.2.3]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[play_2.10.jar:2.2.3]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) ~[akka-actor_2.10.jar:2.2.0]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) ~[akka-actor_2.10.jar:2.2.0]
	... 4 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 't0.to_number' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_65]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[na:1.6.0_65]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_65]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_65]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3558) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3490) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1959) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2109) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2648) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2077) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2228) ~[mysql-connector-java-5.1.10.jar:na]
	at com.jolbox.bonecp.PreparedStatementHandle.executeQuery(PreparedStatementHandle.java:174) ~[bonecp.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.prepareBindExecuteQuery(CQuery.java:377) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.find(CQueryEngine.java:231) ~[avaje-ebeanorm.jar:na]
	... 26 common frames omitted

2015-05-26 18:07:01,361 - [INFO] - from org.avaje.ebean.TXN in play-akka.actor.default-dispatcher-5 
txn[1006] Rollback

2015-05-26 18:07:01,361 - [ERROR] - from play in play-internal-execution-context-2 
Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: Query threw SQLException:Unknown column 't0.to_number' in 'field list' 
Bind values:[SMbfe4db0973714561bb865e4592276ff1] 
Query was:
select t0.message_type c0, t0.id c1, t0.from_number c2, t0.to_number c3, t0.account_id c4, t0.content c5, t0.status c6, t0.created_at c7, t0.updated_at c8 from messages t0 where t0.message_type = 'SMS'  and t0.id = ?   



2015-05-26 18:07:01,365 - [ERROR] - from application in play-internal-execution-context-2 


! @6m9k39gn6 - Internal server error, for (POST) [/status] ->

play.api.Application$$anon$1: Execution exception[[PersistenceException: Query threw SQLException:Unknown column 't0.to_number' in 'field list' 
Bind values:[SMbfe4db0973714561bb865e4592276ff1] 
Query was:
select t0.message_type c0, t0.id c1, t0.from_number c2, t0.to_number c3, t0.account_id c4, t0.content c5, t0.status c6, t0.created_at c7, t0.updated_at c8 from messages t0 where t0.message_type = 'SMS'  and t0.id = ?   

]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.3]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) [play-iteratees_2.10.jar:2.2.3]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
Caused by: javax.persistence.PersistenceException: Query threw SQLException:Unknown column 't0.to_number' in 'field list' 
Bind values:[SMbfe4db0973714561bb865e4592276ff1] 
Query was:
select t0.message_type c0, t0.id c1, t0.from_number c2, t0.to_number c3, t0.account_id c4, t0.content c5, t0.status c6, t0.created_at c7, t0.updated_at c8 from messages t0 where t0.message_type = 'SMS'  and t0.id = ?   


	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:790) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:767) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.find(CQueryEngine.java:250) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findId(DefaultOrmQueryEngine.java:118) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findId(OrmQueryRequest.java:231) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findId(DefaultServer.java:1193) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.find(DefaultServer.java:1046) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.find(DefaultServer.java:1033) ~[avaje-ebeanorm.jar:na]
	at play.db.ebean.Model$Finder.byId(Model.java:261) ~[play-java-ebean_2.10.jar:2.2.3]
	at controllers.Application.status(Application.java:151) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$5$$anonfun$apply$5.apply(routes_routing.scala:101) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$5$$anonfun$apply$5.apply(routes_routing.scala:101) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[play_2.10.jar:2.2.3]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[play_2.10.jar:2.2.3]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) ~[akka-actor_2.10.jar:2.2.0]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) ~[akka-actor_2.10.jar:2.2.0]
	... 4 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 't0.to_number' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_65]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[na:1.6.0_65]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_65]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_65]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3558) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3490) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1959) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2109) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2648) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2077) ~[mysql-connector-java-5.1.10.jar:na]
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2228) ~[mysql-connector-java-5.1.10.jar:na]
	at com.jolbox.bonecp.PreparedStatementHandle.executeQuery(PreparedStatementHandle.java:174) ~[bonecp.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.prepareBindExecuteQuery(CQuery.java:377) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.find(CQueryEngine.java:231) ~[avaje-ebeanorm.jar:na]
	... 26 common frames omitted

2015-05-26 18:09:17,039 - [INFO] - from com.jolbox.bonecp.BoneCP in play-internal-execution-context-1 
Shutting down connection pool...

2015-05-26 18:09:17,083 - [INFO] - from com.jolbox.bonecp.BoneCP in play-internal-execution-context-1 
Connection pool has been shutdown.

2015-05-26 18:09:17,212 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:mysql://localhost:3306/notification_engine

2015-05-26 18:09:17,237 - [INFO] - from org.reflections.Reflections in play-internal-execution-context-1 
Reflections took 23 ms to scan 2 urls, producing 16 keys and 31 values 

2015-05-26 18:09:17,250 - [INFO] - from com.avaje.ebeaninternal.server.core.DefaultServerFactory in play-internal-execution-context-1 
DatabasePlatform name:default platform:mysql

2015-05-26 18:09:17,283 - [INFO] - from com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager in play-internal-execution-context-1 
Entities enhanced[3] subclassed[0]

2015-05-26 18:09:17,285 - [WARN] - from com.avaje.ebean.Ebean in play-internal-execution-context-1 
Existing EbeanServer [default] is being replaced?

2015-05-26 18:09:17,299 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2015-05-26 18:09:17,306 - [INFO] - from com.twilio.sdk.resource.instance.Application in play-akka.actor.default-dispatcher-3 
Sending message request: [To=17734845887, From=+17084876341, Body="Hello", StatusCallback=http://42a2173c.ngrok.io/status]

2015-05-26 18:09:25,801 - [INFO] - from com.twilio.sdk.resource.instance.Application in play-akka.actor.default-dispatcher-7 
Sending message request: [To=17734845887, From=+15005550006, Body="Hello", StatusCallback=http://42a2173c.ngrok.io/status]

2015-05-26 18:09:26,347 - [ERROR] - from controllers.Application in play-akka.actor.default-dispatcher-7 
com.twilio.sdk.TwilioRestException: The From phone number +15005550006 is not a valid, SMS-capable inbound phone number or short code for your account.

2015-05-26 18:09:28,322 - [INFO] - from com.twilio.sdk.resource.instance.Application in play-akka.actor.default-dispatcher-3 
Sending message request: [To=17734845887, From=+17084876341, Body="Hello", StatusCallback=http://42a2173c.ngrok.io/status]

2015-05-26 18:09:50,651 - [INFO] - from com.twilio.sdk.resource.instance.Application in play-akka.actor.default-dispatcher-7 
Sending message request: [To=17734845887, From=+15005550006, Body="Hello", StatusCallback=http://42a2173c.ngrok.io/status]

2015-05-26 18:09:50,861 - [ERROR] - from controllers.Application in play-akka.actor.default-dispatcher-7 
com.twilio.sdk.TwilioRestException: The From phone number +15005550006 is not a valid, SMS-capable inbound phone number or short code for your account.

2015-05-26 18:09:52,211 - [INFO] - from com.twilio.sdk.resource.instance.Application in play-akka.actor.default-dispatcher-7 
Sending message request: [To=17734845887, From=+17084876341, Body="Hello", StatusCallback=http://42a2173c.ngrok.io/status]

2015-05-26 18:10:19,361 - [INFO] - from com.twilio.sdk.resource.instance.Application in play-akka.actor.default-dispatcher-8 
Sending call request: [To=17734845887, From=+15005550006, Url=http://42a2173c.ngrok.io/voice, StatusCallback=http://42a2173c.ngrok.io/callstatus]

2015-05-26 18:10:20,109 - [ERROR] - from controllers.Application in play-akka.actor.default-dispatcher-8 
com.twilio.sdk.TwilioRestException: The source phone number provided, +15005550006, is not yet verified for your account. You may only make calls from phone numbers that you've verified or purchased from Twilio.

2015-05-26 18:10:23,639 - [INFO] - from com.twilio.sdk.resource.instance.Application in play-akka.actor.default-dispatcher-9 
Sending call request: [To=17734845887, From=+17084876341, Url=http://42a2173c.ngrok.io/voice, StatusCallback=http://42a2173c.ngrok.io/callstatus]

2015-05-26 18:25:38,179 - [INFO] - from com.twilio.sdk.resource.instance.Application in play-akka.actor.default-dispatcher-11 
Sending call request: [To=17734845887, From=+15005550006, Url=http://42a2173c.ngrok.io/voice, StatusCallback=http://42a2173c.ngrok.io/callstatus]

2015-05-26 18:25:38,941 - [ERROR] - from controllers.Application in play-akka.actor.default-dispatcher-11 
com.twilio.sdk.TwilioRestException: The source phone number provided, +15005550006, is not yet verified for your account. You may only make calls from phone numbers that you've verified or purchased from Twilio.

2015-05-26 18:25:52,931 - [INFO] - from com.twilio.sdk.resource.instance.Application in play-akka.actor.default-dispatcher-11 
Sending call request: [To=17734845887, From=+17084876341, Url=http://42a2173c.ngrok.io/voice, StatusCallback=http://42a2173c.ngrok.io/callstatus]

2015-05-26 18:26:44,308 - [INFO] - from com.twilio.sdk.resource.instance.Application in play-akka.actor.default-dispatcher-11 
Sending message request: [To=17734845887, From=+15005550006, Body="Hello", StatusCallback=http://42a2173c.ngrok.io/status]

2015-05-26 18:26:44,524 - [ERROR] - from controllers.Application in play-akka.actor.default-dispatcher-11 
com.twilio.sdk.TwilioRestException: The From phone number +15005550006 is not a valid, SMS-capable inbound phone number or short code for your account.

2015-05-26 18:26:47,400 - [INFO] - from com.twilio.sdk.resource.instance.Application in play-akka.actor.default-dispatcher-11 
Sending message request: [To=17734845887, From=+17084876341, Body="Hello", StatusCallback=http://42a2173c.ngrok.io/status]

2015-05-26 18:32:51,361 - [ERROR] - from play in play-internal-execution-context-3 
Cannot invoke the action, eventually got an error: java.lang.NullPointerException: The bean is null?

2015-05-26 18:32:51,370 - [ERROR] - from application in play-internal-execution-context-3 


! @6m9k6jlkl - Internal server error, for (POST) [/status] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: The bean is null?]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.3]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) [play-iteratees_2.10.jar:2.2.3]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
Caused by: java.lang.NullPointerException: The bean is null?
	at com.avaje.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1607) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1598) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1575) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebean.Ebean.update(Ebean.java:496) ~[avaje-ebeanorm.jar:na]
	at controllers.Application.status(Application.java:155) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$5$$anonfun$apply$5.apply(routes_routing.scala:101) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$5$$anonfun$apply$5.apply(routes_routing.scala:101) ~[classes/:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[play_2.10.jar:2.2.3]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[play_2.10.jar:2.2.3]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) ~[akka-actor_2.10.jar:2.2.0]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) ~[akka-actor_2.10.jar:2.2.0]
	... 4 common frames omitted

2015-05-26 18:34:56,618 - [INFO] - from com.jolbox.bonecp.BoneCP in play-internal-execution-context-3 
Shutting down connection pool...

2015-05-26 18:34:56,620 - [INFO] - from com.jolbox.bonecp.BoneCP in play-internal-execution-context-3 
Connection pool has been shutdown.

2015-05-26 18:34:56,725 - [INFO] - from play in play-internal-execution-context-3 
database [default] connected at jdbc:mysql://localhost:3306/notification_engine

2015-05-26 18:34:56,747 - [INFO] - from org.reflections.Reflections in play-internal-execution-context-3 
Reflections took 21 ms to scan 2 urls, producing 16 keys and 31 values 

2015-05-26 18:34:56,766 - [INFO] - from com.avaje.ebeaninternal.server.core.DefaultServerFactory in play-internal-execution-context-3 
DatabasePlatform name:default platform:mysql

2015-05-26 18:34:56,863 - [INFO] - from com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager in play-internal-execution-context-3 
Entities enhanced[3] subclassed[0]

2015-05-26 18:34:56,866 - [WARN] - from com.avaje.ebean.Ebean in play-internal-execution-context-3 
Existing EbeanServer [default] is being replaced?

2015-05-26 18:34:56,881 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2015-05-26 18:34:56,998 - [ERROR] - from play in play-internal-execution-context-3 
Cannot invoke the action, eventually got an error: java.lang.NullPointerException: The bean is null?

2015-05-26 18:34:57,001 - [ERROR] - from application in play-internal-execution-context-3 


! @6m9k70pgl - Internal server error, for (POST) [/status] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: The bean is null?]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.3]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) [play-iteratees_2.10.jar:2.2.3]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
Caused by: java.lang.NullPointerException: The bean is null?
	at com.avaje.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1607) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1598) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1575) ~[avaje-ebeanorm.jar:na]
	at com.avaje.ebean.Ebean.update(Ebean.java:496) ~[avaje-ebeanorm.jar:na]
	at controllers.Application.status(Application.java:156) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$5$$anonfun$apply$5.apply(routes_routing.scala:101) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$5$$anonfun$apply$5.apply(routes_routing.scala:101) ~[classes/:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[play_2.10.jar:2.2.3]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[play_2.10.jar:2.2.3]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10.jar:2.2.3]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[play_2.10.jar:2.2.3]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) ~[akka-actor_2.10.jar:2.2.0]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) ~[akka-actor_2.10.jar:2.2.0]
	... 4 common frames omitted

2015-05-26 18:35:33,206 - [INFO] - from com.jolbox.bonecp.BoneCP in play-internal-execution-context-3 
Shutting down connection pool...

2015-05-26 18:35:33,208 - [INFO] - from com.jolbox.bonecp.BoneCP in play-internal-execution-context-3 
Connection pool has been shutdown.

2015-05-26 18:35:33,303 - [INFO] - from play in play-internal-execution-context-3 
database [default] connected at jdbc:mysql://localhost:3306/notification_engine

2015-05-26 18:35:33,317 - [INFO] - from org.reflections.Reflections in play-internal-execution-context-3 
Reflections took 13 ms to scan 2 urls, producing 16 keys and 31 values 

2015-05-26 18:35:33,329 - [INFO] - from com.avaje.ebeaninternal.server.core.DefaultServerFactory in play-internal-execution-context-3 
DatabasePlatform name:default platform:mysql

2015-05-26 18:35:33,352 - [INFO] - from com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager in play-internal-execution-context-3 
Entities enhanced[3] subclassed[0]

2015-05-26 18:35:33,354 - [WARN] - from com.avaje.ebean.Ebean in play-internal-execution-context-3 
Existing EbeanServer [default] is being replaced?

2015-05-26 18:35:33,364 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2015-05-26 18:38:27,146 - [INFO] - from com.jolbox.bonecp.BoneCP in play-internal-execution-context-3 
Shutting down connection pool...

2015-05-26 18:38:27,148 - [INFO] - from com.jolbox.bonecp.BoneCP in play-internal-execution-context-3 
Connection pool has been shutdown.

2015-05-26 18:38:27,247 - [INFO] - from play in play-internal-execution-context-3 
database [default] connected at jdbc:mysql://localhost:3306/notification_engine

2015-05-26 18:38:27,269 - [INFO] - from org.reflections.Reflections in play-internal-execution-context-3 
Reflections took 21 ms to scan 2 urls, producing 16 keys and 31 values 

2015-05-26 18:38:27,286 - [INFO] - from com.avaje.ebeaninternal.server.core.DefaultServerFactory in play-internal-execution-context-3 
DatabasePlatform name:default platform:mysql

2015-05-26 18:38:27,314 - [INFO] - from com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager in play-internal-execution-context-3 
Entities enhanced[3] subclassed[0]

2015-05-26 18:38:27,315 - [WARN] - from com.avaje.ebean.Ebean in play-internal-execution-context-3 
Existing EbeanServer [default] is being replaced?

2015-05-26 18:38:27,325 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

